name: fb_5_embedded_example
description: "Demonstrates how to use the fb_5_embedded plugin."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  fb_5_embedded:
    path: ../

  cupertino_icons: ^1.0.8
  fbdb: ^1.5.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
