name: fb_5_embedded
description: "Firebird 5 embedded server packaged for Android."
version: 1.0.0
homepage: https://github.com/hipercompl/fb_5_embedded
repository: https://github.com/hipercompl/fb_5_embedded
issue_tracker: https://github.com/hipercompl/fb_5_embedded/issues
topics: firebird database embedded android

screenshots:
  - description: A demo application using embedded Firebird engine.
    path: screenshot.png

environment:
  sdk: ^3.10.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  osenv: ^1.0.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/

  plugin:
    platforms:
      android:
        ffiPlugin: true
